# Generated by Django 5.2.6 on 2025-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='phone',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
