# Generated by Django 5.2.6 on 2025-09-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_medicalrecord_phone_medicalrecord_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
