# Generated by Django 5.2.6 on 2025-09-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_medicalrecord_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
    ]
