# Generated by Django 5.0.4 on 2025-08-04 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='established_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='registration_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['hospital_name'], name='hospital_ho_hospita_21112d_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['registration_number'], name='hospital_ho_registr_67003b_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['city'], name='hospital_ho_city_539e0f_idx'),
        ),
    ]
