# Generated by Django 5.0.4 on 2025-08-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospital_options_alter_hospital_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
