# Generated by Django 5.0.4 on 2025-08-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('address', models.TextField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveSmallIntegerField()),
                ('license', models.CharField(max_length=50, unique=True)),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('idproof', models.FileField(upload_to='idproofs/')),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'indexes': [models.Index(fields=['email'], name='doctor_doct_email_47f878_idx'), models.Index(fields=['username'], name='doctor_doct_usernam_5bcaf2_idx'), models.Index(fields=['license'], name='doctor_doct_license_424aec_idx')],
            },
        ),
    ]
